"""add_coproductionproc_gameid

Revision ID: 0462dcc06662
Revises: a4e4e44c87f8
Create Date: 2023-02-27 16:48:30.407530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0462dcc06662'
down_revision = 'a4e4e44c87f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coproductionprocess', sa.Column('game_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coproductionprocess', 'game_id')
    # ### end Alembic commands ###
