"""additionalEmails

Revision ID: 0f727d655ce1
Revises: 5286216dd426
Create Date: 2022-07-22 09:24:07.138007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f727d655ce1'
down_revision = '5286216dd426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('additionalEmails', sa.ARRAY(sa.String()), server_default='{}', nullable=True))
    op.drop_column('user', 'zoneinfo')
    op.drop_column('user', 'locale')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('locale', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('zoneinfo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'additionalEmails')
    # ### end Alembic commands ###
