"""add_coproid_usernotifications

Revision ID: 12a0ced8c03a
Revises: 0462dcc06662
Create Date: 2023-03-08 14:27:39.427505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12a0ced8c03a'
down_revision = '0462dcc06662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usernotification', sa.Column('coproductionprocess_id', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usernotification', 'coproductionprocess_id')
    # ### end Alembic commands ###
