"""addingFieldHideGuide

Revision ID: 12a460d28a99
Revises: 997e03d380bd
Create Date: 2023-04-18 11:31:54.754206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a460d28a99'
down_revision = '997e03d380bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coproductionprocess', sa.Column('hideguidechecklist', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coproductionprocess', 'hideguidechecklist')
    # ### end Alembic commands ###
