"""addingparticipationrequesttable

Revision ID: 130d91688f27
Revises: 92d6a7c2bd6f
Create Date: 2023-07-03 11:37:46.753141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '130d91688f27'
down_revision = '92d6a7c2bd6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participationrequest',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('coproductionprocess_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('razon', sa.String(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['user.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participationrequest')
    # ### end Alembic commands ###
