"""Adding_requirements_copro

Revision ID: 1d0b4b775849
Revises: d435fdbaca19
Create Date: 2023-06-26 15:18:00.479846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0b4b775849'
down_revision = 'd435fdbaca19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coproductionprocess', sa.Column('requirements', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coproductionprocess', 'requirements')
    # ### end Alembic commands ###
