"""Add_interation_governmental_model

Revision ID: 1e7f299eebb8
Revises: 12a460d28a99
Create Date: 2023-04-24 18:45:15.353966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7f299eebb8'
down_revision = '12a460d28a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coproductionprocess', sa.Column('intergovernmental_model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coproductionprocess', 'intergovernmental_model')
    # ### end Alembic commands ###
