"""add_story

Revision ID: 1f4674af7c12
Revises: a442968a0c8b
Create Date: 2023-02-17 12:13:37.938393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f4674af7c12'
down_revision = 'a442968a0c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('coproductionprocess_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('data_story', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coproductionprocess_id'], ['coproductionprocess.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story')
    # ### end Alembic commands ###
