"""fix_tag_uuid

Revision ID: 208738f13dce
Revises: 8575af21e211
Create Date: 2023-05-05 09:20:31.852087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208738f13dce'
down_revision = '8575af21e211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
