"""add_notification_language

Revision ID: 270a1c42c6fc
Revises: e9898fd85100
Create Date: 2023-01-25 10:33:22.927256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270a1c42c6fc'
down_revision = 'e9898fd85100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('language', sa.String(), nullable=True))
    op.drop_constraint('notification_event_key', 'notification', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('notification_event_key', 'notification', ['event'])
    op.drop_column('notification', 'language')
    # ### end Alembic commands ###
