"""second

Revision ID: 30aca9fa633a
Revises: ae09af8c9990
Create Date: 2022-05-17 11:08:46.256111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30aca9fa633a'
down_revision = 'ae09af8c9990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('asset_coproductionprocess_id_fkey', 'asset', type_='foreignkey')
    op.drop_constraint('asset_creator_id_fkey', 'asset', type_='foreignkey')
    op.drop_constraint('asset_task_id_fkey', 'asset', type_='foreignkey')
    op.create_foreign_key(None, 'asset', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'asset', 'coproductionprocess', ['coproductionprocess_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'asset', 'user', ['creator_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.drop_constraint('association_team_role_team_id_fkey', 'association_team_role', type_='foreignkey')
    op.drop_constraint('association_team_role_role_id_fkey', 'association_team_role', type_='foreignkey')
    op.create_foreign_key(None, 'association_team_role', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'association_team_role', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('association_user_role_role_id_fkey', 'association_user_role', type_='foreignkey')
    op.drop_constraint('association_user_role_user_id_fkey', 'association_user_role', type_='foreignkey')
    op.create_foreign_key(None, 'association_user_role', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'association_user_role', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('association_user_team_user_id_fkey', 'association_user_team', type_='foreignkey')
    op.drop_constraint('association_user_team_team_id_fkey', 'association_user_team', type_='foreignkey')
    op.create_foreign_key(None, 'association_user_team', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'association_user_team', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('coproductionprocess_creator_id_fkey', 'coproductionprocess', type_='foreignkey')
    op.create_foreign_key(None, 'coproductionprocess', 'user', ['creator_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'coproductionprocess', 'role', ['default_role_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.drop_column('coproductionprocess', 'artefact_id')
    op.drop_constraint('internalasset_id_fkey', 'internalasset', type_='foreignkey')
    op.create_foreign_key(None, 'internalasset', 'asset', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('objective_phase_id_fkey', 'objective', type_='foreignkey')
    op.create_foreign_key(None, 'objective', 'phase', ['phase_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('objective_prerequisites_objective_a_id_fkey', 'objective_prerequisites', type_='foreignkey')
    op.create_foreign_key(None, 'objective_prerequisites', 'objective', ['objective_a_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('phase_coproductionprocess_id_fkey', 'phase', type_='foreignkey')
    op.create_foreign_key(None, 'phase', 'coproductionprocess', ['coproductionprocess_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('phase_prerequisites_phase_a_id_fkey', 'phase_prerequisites', type_='foreignkey')
    op.create_foreign_key(None, 'phase_prerequisites', 'phase', ['phase_a_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('role_coproductionprocess_id_fkey', 'role', type_='foreignkey')
    op.create_foreign_key(None, 'role', 'coproductionprocess', ['coproductionprocess_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('task_prerequisites_task_a_id_fkey', 'task_prerequisites', type_='foreignkey')
    op.create_foreign_key(None, 'task_prerequisites', 'task', ['task_a_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('team_creator_id_fkey', 'team', type_='foreignkey')
    op.create_foreign_key(None, 'team', 'user', ['creator_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.create_foreign_key('team_creator_id_fkey', 'team', 'user', ['creator_id'], ['id'])
    op.drop_constraint(None, 'task_prerequisites', type_='foreignkey')
    op.create_foreign_key('task_prerequisites_task_a_id_fkey', 'task_prerequisites', 'task', ['task_a_id'], ['id'])
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.create_foreign_key('role_coproductionprocess_id_fkey', 'role', 'coproductionprocess', ['coproductionprocess_id'], ['id'])
    op.drop_constraint(None, 'phase_prerequisites', type_='foreignkey')
    op.create_foreign_key('phase_prerequisites_phase_a_id_fkey', 'phase_prerequisites', 'phase', ['phase_a_id'], ['id'])
    op.drop_constraint(None, 'phase', type_='foreignkey')
    op.create_foreign_key('phase_coproductionprocess_id_fkey', 'phase', 'coproductionprocess', ['coproductionprocess_id'], ['id'])
    op.drop_constraint(None, 'objective_prerequisites', type_='foreignkey')
    op.create_foreign_key('objective_prerequisites_objective_a_id_fkey', 'objective_prerequisites', 'objective', ['objective_a_id'], ['id'])
    op.drop_constraint(None, 'objective', type_='foreignkey')
    op.create_foreign_key('objective_phase_id_fkey', 'objective', 'phase', ['phase_id'], ['id'])
    op.drop_constraint(None, 'internalasset', type_='foreignkey')
    op.create_foreign_key('internalasset_id_fkey', 'internalasset', 'asset', ['id'], ['id'])
    op.add_column('coproductionprocess', sa.Column('artefact_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'coproductionprocess', type_='foreignkey')
    op.drop_constraint(None, 'coproductionprocess', type_='foreignkey')
    op.create_foreign_key('coproductionprocess_creator_id_fkey', 'coproductionprocess', 'user', ['creator_id'], ['id'])
    op.drop_constraint(None, 'association_user_team', type_='foreignkey')
    op.drop_constraint(None, 'association_user_team', type_='foreignkey')
    op.create_foreign_key('association_user_team_team_id_fkey', 'association_user_team', 'team', ['team_id'], ['id'])
    op.create_foreign_key('association_user_team_user_id_fkey', 'association_user_team', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'association_user_role', type_='foreignkey')
    op.drop_constraint(None, 'association_user_role', type_='foreignkey')
    op.create_foreign_key('association_user_role_user_id_fkey', 'association_user_role', 'user', ['user_id'], ['id'])
    op.create_foreign_key('association_user_role_role_id_fkey', 'association_user_role', 'role', ['role_id'], ['id'])
    op.drop_constraint(None, 'association_team_role', type_='foreignkey')
    op.drop_constraint(None, 'association_team_role', type_='foreignkey')
    op.create_foreign_key('association_team_role_role_id_fkey', 'association_team_role', 'role', ['role_id'], ['id'])
    op.create_foreign_key('association_team_role_team_id_fkey', 'association_team_role', 'team', ['team_id'], ['id'])
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.create_foreign_key('asset_task_id_fkey', 'asset', 'task', ['task_id'], ['id'])
    op.create_foreign_key('asset_creator_id_fkey', 'asset', 'user', ['creator_id'], ['id'])
    op.create_foreign_key('asset_coproductionprocess_id_fkey', 'asset', 'coproductionprocess', ['coproductionprocess_id'], ['id'])
    # ### end Alembic commands ###
