"""AddRankingStoryTable

Revision ID: 3772821fd934
Revises: 7b1b9f388079
Create Date: 2023-05-29 13:48:04.158719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3772821fd934'
down_revision = '7b1b9f388079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('ratings_count', sa.Integer(), nullable=True))
    op.alter_column('story', 'rating',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=2, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('story', 'rating',
               existing_type=sa.Numeric(precision=2, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('story', 'ratings_count')
    # ### end Alembic commands ###
