"""change_enum_coprostate

Revision ID: 48429167d6dd
Revises: 5c3b601741f8
Create Date: 2022-09-08 15:03:18.627249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48429167d6dd'
down_revision = '5c3b601741f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coproductionprocess', sa.Column('status', sa.Enum('awaiting', 'in_progress', 'finished', name='status', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coproductionprocess', 'status')
    # ### end Alembic commands ###
