"""add_notifications_type

Revision ID: 563e95d5c042
Revises: c467f4fc539a
Create Date: 2023-02-02 10:22:00.831336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563e95d5c042'
down_revision = 'c467f4fc539a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coproductionprocessnotification', sa.Column('claim_type', sa.Enum('management', 'development', 'exploitation', name='claimtypes', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coproductionprocessnotification', 'claim_type')
    # ### end Alembic commands ###
