"""add_default_copro_State

Revision ID: 5c3b601741f8
Revises: b8882a0a86d7
Create Date: 2022-09-08 11:37:42.700284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3b601741f8'
down_revision = 'b8882a0a86d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coproductionprocess', 'copro_state',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coproductionprocess', 'copro_state',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
