"""addingkeywordsStories

Revision ID: 798a541debc8
Revises: 0ad3647edd58
Create Date: 2023-06-06 08:59:12.831461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '798a541debc8'
down_revision = '0ad3647edd58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('story_keywords',
    sa.Column('story_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('keyword_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id', 'keyword_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_keywords')
    op.drop_table('keyword')
    # ### end Alembic commands ###
