"""add_point_tasks

Revision ID: 7bbdc4cbbdb5
Revises: 563e95d5c042
Create Date: 2023-02-02 14:48:24.305008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bbdc4cbbdb5'
down_revision = '563e95d5c042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('management', sa.Integer(), nullable=True))

    #Pongo los valores por defecto de management:
    op.execute("UPDATE task SET management = 0")
    op.alter_column('task', 'management', nullable=False)

    op.add_column('task', sa.Column('development', sa.Integer(), nullable=True))
    #Pongo los valores por defecto de development:
    op.execute("UPDATE task SET development = 0")
    op.alter_column('task', 'development', nullable=False)

    op.add_column('task', sa.Column('exploitation', sa.Integer(), nullable=True))
    #Pongo los valores por defecto de exploitation:
    op.execute("UPDATE task SET exploitation = 0")
    op.alter_column('task', 'exploitation', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'exploitation')
    op.drop_column('task', 'development')
    op.drop_column('task', 'management')
    # ### end Alembic commands ###
