"""copro_state_removed

Revision ID: 801536322b76
Revises: 48429167d6dd
Create Date: 2022-09-15 10:16:39.952976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801536322b76'
down_revision = '48429167d6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coproductionprocess', 'copro_state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coproductionprocess', sa.Column('copro_state', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
