"""edit_tags

Revision ID: 8575af21e211
Revises: 7e3153a426bc
Create Date: 2023-05-04 11:47:57.016542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8575af21e211'
down_revision = '7e3153a426bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('name', sa.String(), nullable=False))
    op.add_column('tag', sa.Column('description', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'tag', ['name'])
    op.drop_column('tag', 'description_translations')
    op.drop_column('tag', 'name_translations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('name_translations', postgresql.HSTORE(text_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tag', sa.Column('description_translations', postgresql.HSTORE(text_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tag', type_='unique')
    op.drop_column('tag', 'description')
    op.drop_column('tag', 'name')
    # ### end Alembic commands ###
