"""adding_icon_notification

Revision ID: 86b8b82d8317
Revises: 79e7eb1f053f
Create Date: 2023-01-12 10:55:06.949771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b8b82d8317'
down_revision = '79e7eb1f053f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'coproductionprocessnotification', 'notification', ['notification_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'coproductionprocessnotification', 'coproductionprocess', ['coproductionprocess_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('notification', sa.Column('icon', sa.String(), nullable=True))
    op.create_foreign_key(None, 'usernotification', 'user', ['user_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'usernotification', 'notification', ['notification_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usernotification', type_='foreignkey')
    op.drop_constraint(None, 'usernotification', type_='foreignkey')
    op.drop_column('notification', 'icon')
    op.drop_constraint(None, 'coproductionprocessnotification', type_='foreignkey')
    op.drop_constraint(None, 'coproductionprocessnotification', type_='foreignkey')
    # ### end Alembic commands ###
