"""Adding_ispublic_to_coproductionpro

Revision ID: 8beab7a600b4
Revises: 798a541debc8
Create Date: 2023-06-07 16:27:18.916033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8beab7a600b4'
down_revision = '798a541debc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coproductionprocess', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coproductionprocess', 'is_public')
    # ### end Alembic commands ###
