"""changenamecolumnusernotifications

Revision ID: 92d6a7c2bd6f
Revises: b63c3c410007
Create Date: 2023-06-30 12:48:39.575759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d6a7c2bd6f'
down_revision = 'b63c3c410007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usernotification', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.drop_column('usernotification', 'isArchived')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usernotification', sa.Column('isArchived', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('usernotification', 'is_archived')
    # ### end Alembic commands ###
