"""addingOpFieldsDefUsers

Revision ID: 997e03d380bd
Revises: 90937d7439be
Create Date: 2023-04-03 12:53:31.743316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997e03d380bd'
down_revision = '90937d7439be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coproductionprocess', sa.Column('hasAddAnOrganization', sa.Boolean(), nullable=True))
    op.add_column('coproductionprocess', sa.Column('skipResourcesStep', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coproductionprocess', 'skipResourcesStep')
    op.drop_column('coproductionprocess', 'hasAddAnOrganization')
    # ### end Alembic commands ###
