"""add_coproclone_story

Revision ID: a4e4e44c87f8
Revises: cce309c9b741
Create Date: 2023-02-21 14:33:03.903739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4e4e44c87f8'
down_revision = 'cce309c9b741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('coproductionprocess_cloneforpub_id', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'coproductionprocess_cloneforpub_id')
    # ### end Alembic commands ###
