"""addingActhiveState_to_usernotifications

Revision ID: b63c3c410007
Revises: 1d0b4b775849
Create Date: 2023-06-30 11:28:35.368963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63c3c410007'
down_revision = '1d0b4b775849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usernotification', sa.Column('isArchived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usernotification', 'isArchived')
    # ### end Alembic commands ###
