"""adding_copro_state

Revision ID: b8882a0a86d7
Revises: 0f727d655ce1
Create Date: 2022-09-08 09:56:37.345471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8882a0a86d7'
down_revision = '0f727d655ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coproductionprocess', sa.Column('copro_state', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coproductionprocess', 'copro_state')
    # ### end Alembic commands ###
