"""dimensions_optional

Revision ID: c1e8fe12849f
Revises: a442968a0c8b
Create Date: 2023-02-15 15:59:29.708296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e8fe12849f'
down_revision = 'a442968a0c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
