"""add_asset_user_notification

Revision ID: c467f4fc539a
Revises: b4983b08c81d
Create Date: 2023-01-27 14:59:15.522978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c467f4fc539a'
down_revision = 'b4983b08c81d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coproductionprocessnotification', sa.Column('asset_id', sa.String(), nullable=True))
    op.add_column('coproductionprocessnotification', sa.Column('user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coproductionprocessnotification', 'user_id')
    op.drop_column('coproductionprocessnotification', 'asset_id')
    # ### end Alembic commands ###
