"""add_flag_publicationtocopro

Revision ID: cce309c9b741
Revises: 1f4674af7c12
Create Date: 2023-02-21 09:44:44.175394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce309c9b741'
down_revision = '1f4674af7c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coproductionprocess', sa.Column('is_part_of_publication', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'story', 'coproductionprocess', ['coproductionprocess_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'story', type_='foreignkey')
    op.drop_column('coproductionprocess', 'is_part_of_publication')
    # ### end Alembic commands ###
