"""treeitems

Revision ID: cf74bab0cdff
Revises: 
Create Date: 2022-06-20 13:18:48.827350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf74bab0cdff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coproductionprocess',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('schema_used', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('logotype', sa.String(), nullable=True),
    sa.Column('aim', sa.Text(), nullable=True),
    sa.Column('idea', sa.Text(), nullable=True),
    sa.Column('challenges', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.String(), nullable=True),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('phases_count', sa.Integer(), nullable=True),
    sa.Column('assets_count', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('default_team_type', sa.Enum('citizen', 'public_administration', 'nonprofit_organization', 'forprofit_organization', name='roletypes', native_enum=False), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('name_translations', postgresql.HSTORE(text_type=sa.Text()), nullable=True),
    sa.Column('description_translations', postgresql.HSTORE(text_type=sa.Text()), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('logotype', sa.String(), nullable=True),
    sa.Column('creator_id', sa.String(), nullable=True),
    sa.Column('team_creation_permission', sa.Enum('administrators', 'members', 'anyone', name='teamcreationpermissions', native_enum=False), server_default='administrators', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treeitem',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.String(length=70), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('creator_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('awaiting', 'in_progress', 'finished', name='status', native_enum=False), nullable=True),
    sa.Column('disabler_id', sa.String(), nullable=True),
    sa.Column('disabled_on', sa.DateTime(), nullable=True),
    sa.Column('from_item', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('from_schema', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('path_ids', sa.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['disabler_id'], ['user.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('zoneinfo', sa.String(), nullable=True),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coproductionprocess_administrators',
    sa.Column('coproductionprocess_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['coproductionprocess_id'], ['coproductionprocess.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coproductionprocess_id', 'user_id')
    )
    op.create_table('organization_administrators',
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'user_id')
    )
    op.create_table('phase',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_part_of_codelivery', sa.Boolean(), nullable=True),
    sa.Column('coproductionprocess_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('assets_count', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['coproductionprocess_id'], ['coproductionprocess.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['treeitem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('logotype', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('citizen', 'public_administration', 'nonprofit_organization', 'forprofit_organization', name='roletypes', native_enum=False), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=True),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('users_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('treeitem_prerequisites',
    sa.Column('treeitem_a_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('treeitem_b_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['treeitem_a_id'], ['treeitem.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treeitem_b_id'], ['treeitem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('treeitem_a_id', 'treeitem_b_id')
    )
    op.create_table('association_user_team',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('team_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.create_table('objective',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('phase_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('assets_count', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['treeitem.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phase_id'], ['phase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('team_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('coproductionprocess_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('treeitem_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('edit_treeitem_permission', sa.Boolean(), nullable=True),
    sa.Column('delete_treeitem_permission', sa.Boolean(), nullable=True),
    sa.Column('access_assets_permission', sa.Boolean(), nullable=True),
    sa.Column('create_assets_permission', sa.Boolean(), nullable=True),
    sa.Column('delete_assets_permission', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coproductionprocess_id'], ['coproductionprocess.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treeitem_id'], ['treeitem.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_administrators',
    sa.Column('team_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.create_table('task',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('problemprofiles', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('objective_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('assets_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['treeitem.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objective_id'], ['objective.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('coproductionprocess_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('creator_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coproductionprocess_id'], ['coproductionprocess.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('externalasset',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('icon_path', sa.String(), nullable=True),
    sa.Column('externalinterlinker_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internalasset',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('external_asset_id', sa.String(), nullable=True),
    sa.Column('softwareinterlinker_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('knowledgeinterlinker_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'asset', 'user', ['creator_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'coproductionprocess', 'user', ['creator_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'coproductionprocess', 'organization', ['organization_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'organization', 'user', ['creator_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'permission', 'user', ['creator_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'team', 'user', ['creator_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'treeitem', 'user', ['creator_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'treeitem', 'user', ['disabler_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('internalasset')
    op.drop_table('externalasset')
    op.drop_table('asset')
    op.drop_table('task')
    op.drop_table('team_administrators')
    op.drop_table('permission')
    op.drop_table('objective')
    op.drop_table('association_user_team')
    op.drop_table('treeitem_prerequisites')
    op.drop_table('team')
    op.drop_table('phase')
    op.drop_table('organization_administrators')
    op.drop_table('coproductionprocess_administrators')
    op.drop_table('user')
    op.drop_table('treeitem')
    op.drop_table('organization')
    op.drop_table('coproductionprocess')

    op.drop_constraint(None, 'treeitem', type_='foreignkey')
    op.drop_constraint(None, 'treeitem', type_='foreignkey')
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_constraint(None, 'permission', type_='foreignkey')
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_constraint(None, 'coproductionprocess', type_='foreignkey')
    op.drop_constraint(None, 'coproductionprocess', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    # ### end Alembic commands ###
