"""addingranking

Revision ID: d435fdbaca19
Revises: 8beab7a600b4
Create Date: 2023-06-11 08:26:22.277627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd435fdbaca19'
down_revision = '8beab7a600b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coproductionprocess', sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True))
    op.add_column('coproductionprocess', sa.Column('ratings_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coproductionprocess', 'ratings_count')
    op.drop_column('coproductionprocess', 'rating')
    # ### end Alembic commands ###
