"""add_notifications

Revision ID: eaa01ef9d7f7
Revises: 801536322b76
Create Date: 2022-12-19 01:47:55.573234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eaa01ef9d7f7'
down_revision = '801536322b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('channel', sa.Enum('in_app', 'email', 'chat', name='channeltypes', native_enum=False), nullable=False),
    sa.Column('template', sa.String(), nullable=True),
    sa.Column('list_vars', sa.String(), nullable=True),
    sa.Column('url_boton', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('notifier_id', sa.String(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['notifier_id'], ['user.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['resource_id'], ['asset.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
