"""AddingAggreeTermsUse

Revision ID: efcb7da18049
Revises: 9d6f323092f8
Create Date: 2023-09-26 14:58:22.632373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efcb7da18049'
down_revision = '9d6f323092f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('agreeTermsOfUse', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'agreeTermsOfUse')
    # ### end Alembic commands ###
